# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Max Böck - Frontend Web Developer
description: > 
  Max Böck is a professional frontend developer based in Vienna, Austria.
baseurl: ""
url: https://mxb.at
email: hello@mxb.at

# SEO/Meta settings
logo: /assets/images/logo.png
author: mxbck
twitter:
  username: mxbck
github:
  username: maxboeck
facebook:
  admins: 100000249390604
social:
  name: Max Böck
  links:
    - https://twitter.com/mxbck
    - https://github.com/maxboeck
    - https://keybase.io/mxb
seo:
  name: Max Böck
  type: Person
analytics:
  id: UA-8695781-1

#Custom collections
collections:
  projects:
    output: true
    permalink: /project/:path/

# Pagination
paginate: 30
paginate_path: "/blog/page/:num/"
permalink: /blog/:slug/

# Markdown settings
markdown: kramdown
highlighter: rouge

# Includes
include:
  - _pages

# Build settings
exclude:
  - package.json
  - gulpfile.babel.js
  - README.md
  - LICENSE
  - _tasks
  - assets
  - node_modules
  - Gemfile
  - Gemfile.lock
  - "*.sublime-*"

#Files generated by Gulp
keep_files:
  - assets

# Plugin settings
gems:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-email-protect
