# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Max Böck - Frontend Web Developer
description: > 
  Max Böck is a professional frontend developer based in Vienna, Austria.
baseurl: ""
url: https://mxb.at
email: hello@mxb.at
twitter_username: "@mxbck"
analytics_id: UA-8695781-1

#Custom collections
collections:
  projects:
    output: true
    permalink: /project/:path/

# Pagination
paginate: 30
paginate_path: "/blog/page/:num/"
permalink: /blog/:slug/

# Markdown settings
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

# Sass settings
sass:
  add_charset: true
  sass_dir: _assets/sass
  style: :compressed

# Build settings
exclude:
  - package.json
  - gulpfile.babel.js
  - README.md
  - LICENSE
  - _tasks
  - assets
  - node_modules
  - Gemfile
  - Gemfile.lock
  - "*.sublime-*"

#Files generated by Gulp
keep_files:
  - assets

# Plugin settings
gems:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
